#!/usr/bin/env php
<?php

require_once __DIR__.'/ECommerceKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new ECommerceKernel('test', true);

$application = new Application($kernel);
$application->run();
