imports:
  - { resource: config.yml }

app.config:
  toolbar: false
  test: {}

zend.config:
  logger:
    priority: debug

doctrine.dbal:
  connections:
    default:
      dbname:                       symfony2_ecommerce_test
      user:                         root
      password:                     ~

test_session.config: ~

